# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: cluster-connect-gateway
description: A Helm chart for Cluster Connect Gateway
type: application
version: 1.2.5
annotations:
  revision: 72a6788fbf8cc480e3aedcd083a1acd4c3165544
  created: "2025-11-19T22:00:28Z"
appVersion: 1.2.5
dependencies:
  - name: "connect-agent"
    repository: "file://./charts/connect-agent"
    version: 0.1.0
