# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---

name: CO Integration test CI Pipeline

on:
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  integration-smoke-test:
    permissions:
      contents: read
    runs-on: ubuntu-24.04-16core-64GB
    if: true
    env:
      VERSION: ${{ github.head_ref }}  # Use the component branch that triggered the action for the test
    steps:
      - name: Checkout orch ci
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          token: ${{ secrets.SYS_EMF_GH_TOKEN || github.token }}
          repository: open-edge-platform/orch-ci
          path: ci
          ref: "main"
          persist-credentials: false

      - name: Checkout cluster-tests for integration tests
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          token: ${{ secrets.SYS_EMF_GH_TOKEN || github.token }}
          repository: open-edge-platform/cluster-tests
          path: cluster-tests
          ref: "main"
          persist-credentials: false

      - name: Bootstrap CI environment
        uses: ./ci/.github/actions/bootstrap
        with:
          gh_token: ${{ secrets.SYS_EMF_GH_TOKEN }}

      - name: Run make test with additional config
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          cd cluster-tests
          ADDITIONAL_CONFIG="{\"components\":[{\"name\":\"cluster-connect-gateway\", \"skip-local-build\": false, \"git-repo\": {\"version\":\"${VERSION}\"}}]}" make test
